### ISSUE TITLE
SHA-256 is incredible unsecure.

### ISSUE THREAD

**Issue by brunobritodev** [andrebaltieri/SecureIdentity#1]
[SHA-256](https://github.com/andrebaltieri/SecureIdentity/blob/1d7bbcd3100aae59dc87d419aaf57a40464542f5/SecureIdentity/Password/PasswordHasher.cs#L24) is not a secure Algorithm for Password. It was created for another goal.

There are a plenty of content showing how to hash password. Argon2id is the best choice since 2014. https://password-hashing.net/

In some tests takes only 45 min to break a password of 9 length. 
<img width="1200" alt="2021-06-21_10-57-10" src="https://user-images.githubusercontent.com/7241156/122777570-8abaa000-d282-11eb-9ad6-1762b7bf7e5f.png">

https://www.pcworld.com/article/3605688/how-to-create-strong-secure-passwords.html

https://www.brunobrito.net.br/seguranca-como-armazenar-senha/

**Comment by andrebaltieri** [comment]
Great! Will appreciate your PR with the purposed changes!

**Comment by andrebaltieri** [comment]
No more information or PR was provided
